import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "@/trpc/react";
import MainLayout from "@/components/layout/main";
import { Toaster } from "sonner";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <head>
        <link rel="manifest" href="manifest.json" />
      </head>
      <body>
        <TRPCReactProvider>
          <MainLayout>{children}</MainLayout>
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
